services:
  api:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: hris_user
      POSTGRES_PASSWORD: hris_password
      POSTGRES_DB: hris_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: